### ISSUE TITLE
How to use this program?

### ISSUE THREAD

**Issue by Rudigus** [izarooni/WzVisualizer#1]
Well, I've built the .exe with Visual Studio, but when I try to load WZ, it says that maybe the WZ version is wrong. The GM Handtool written in Delphi doesn't need WZ version, and to be honest, I don't know where to get that info. I tried putting from 0 to 105 inclusive, but none worked. Any thoughts?

**Comment by izarooni** [comment]
You're right, I'm not sure why I added a manual WZ version check. The version is usually read when parsing the WZ file. I'll put out a fix for this soon.

**Comment by izarooni** [comment]
Pull the latest commit and let me know if that helps at all. I'll be doing some more testing with different maple versions. I've tested 83, 95, 145 and 179 which all seem to be working minus some images not showing for the higher versions.

**Comment by Rudigus** [comment]
Now I'm getting: "Failed to parse the WZ file. Perhaps the wrong WZ encryption is being used?". I'm providing GMS's newest WZ, and getting that error. (actually giving maplestory's appdata folder to the program)

**Comment by izarooni** [comment]
I'll see if I can update my GMS and test myself. The latest version I have is v199 (which the program seems to be able to load fine) and the latest update seem to be v203 as of around 3 days ago.
If you'd like to try things yourself:

- Does loading using the Delphi GM Handtool program work?
- Are you able to open any files with any version of HaRepacker or [HaRepacker-Ressurected](https://github.com/lastbattle/Harepacker-resurrected)?
- Try selecting BMS or CLASSIC from the drop down menu

Also maybe check the decryption success rate here or get rid of it entirely and see what happens:
https://github.com/izarooni/WzVisualizer/blob/master/WzVisualizer/GUI/Form1.cs#L654

**Comment by Rudigus** [comment]
Now it worked. It was a bit slow to load, but that's no major problem. I think maybe I had Maplestory or GM Handtool on when I tried to load your tool, and they conflicted. Thanks for the help!

**Comment by Rudigus** [comment]
Do you know where I can learn about this whole WZ thing? I want to make a tool like yours, but with different sections and information.

**Comment by izarooni** [comment]
I'm actually still very new to the C# language, the library [MapleLib](https://github.com/haha01haha01/MapleLib) code that was used to parse the WZ files is very old and has pretty much no documentation so I had to read and reference code in HaRepacker to figure out how and what data structures to use. I didn't make any of the code that has to do with parsing WZ files.

The design of the program I made with Visual Studio's design view which is pretty simple given that you just drag and drop components that you want then size and position them as you want.
I used to make a lot of programs in Java so making this was somewhat more easy for me.
Google is always your friend when you run into a problem, I used to have dozens of tabs for questions I needed help on so don't be ashamed about asking questions!

If you want to ask me anything, you can message me on Discord: izarooni#4063
