### ISSUE TITLE
[Enhancement] Suggestion for searching items using filter system

### ISSUE THREAD

**Issue by itay0246** [izarooni/WzVisualizer#4]
pls make it possible to search item by using filter that u can tick the item properties
For example i search for item without a name "NO-NAME" and i will be able to tick by using filter system the propertie "Cash=1"
Thank you for the software, appreciate the read and help

**Comment by izarooni** [comment]
Thanks for the suggestion! I made an update which lets you search for multiple text by using multiple lines.

In this screenshot I search for "NO-NAME" and "cash=1". You can add as many lines as needed.
I replaced searching with the enter key with a button so that multiple lines can be input.
[WzVisualizer.zip](https://github.com/izarooni/WzVisualizer/files/5248701/WzVisualizer.zip)

Let me know if there are any issues.

![image](https://user-images.githubusercontent.com/8017468/93653781-a03f2880-f9d7-11ea-84f3-04c048b77d44.png)

**Comment by itay0246** [comment]
> Thanks for the suggestion! I made an update which lets you search for multiple text by using multiple lines.
> 
> In this screenshot I search for "NO-NAME" and "cash=1". You can add as many lines as needed.
> I replaced searching with the enter key with a button so that multiple lines can be input.
> [WzVisualizer.zip](https://github.com/izarooni/WzVisualizer/files/5248701/WzVisualizer.zip)
> 
> Let me know if there are any issues.
> 
> ![image](https://user-images.githubusercontent.com/8017468/93653781-a03f2880-f9d7-11ea-84f3-04c048b77d44.png)

Thank you for the update but right now it seems like the search is not working properly and also all the "NO-NAME" items are being filled with white blank box instead of the nick "NO-NAME"
Example:
The item im looking for:
![image](https://user-images.githubusercontent.com/43476587/93668020-93cbd600-fa92-11ea-98d5-d74ca4b6ceec.png)
My search & result:
![image](https://user-images.githubusercontent.com/43476587/93668073-f02ef580-fa92-11ea-9fee-2d7f1b1ce0cd.png)
No-Name issue:
![image](https://user-images.githubusercontent.com/43476587/93668089-13f23b80-fa93-11ea-8337-b65853dbd9d4.png)
***Note:** just letting you know the no-name issue working fine on the last version you released
Also i hope this search function will work on every other category like mobs,npc,reactors,etc... Thanks :)

**Comment by izarooni** [comment]
Hey! Sorry for the late update. I've made the following changes:
- Name column shows NO-NAME when not available
- Search box height becoming to small (vertically) when text is empty
- Added the version number to the window title
- Search button location now moves relative to the window size

The multi-line search function should work on every category (it does for me).
Let me know if there are any problems!

[WzVisualizer.zip](https://github.com/izarooni/WzVisualizer/files/5344484/WzVisualizer.zip)

**Comment by itay0246** [comment]
> Hey! Sorry for the late update. I've made the following changes:
> 
> * Name column shows NO-NAME when not available
> * Search box height becoming to small (vertically) when text is empty
> * Added the version number to the window title
> * Search button location now moves relative to the window size
> 
> The multi-line search function should work on every category (it does for me).
> Let me know if there are any problems!
> 
> [WzVisualizer.zip](https://github.com/izarooni/WzVisualizer/files/5344484/WzVisualizer.zip)

Ok thank you so much for the update i will check it out

Edit: When Im trying to search for items i dont get any search result although the item is exist i even tried to use clipboard and nothing works
**Note:** tried it on weapons/caps
Item:
![image](https://user-images.githubusercontent.com/43476587/95679359-f2402c00-0bda-11eb-9408-fada3527f8a6.png)
My Search while using clipboard: 
![image](https://user-images.githubusercontent.com/43476587/95679382-23b8f780-0bdb-11eb-834d-c3b0844f53cb.png)

**Comment by izarooni** [comment]
I was waiting for an update but I didn't realize you edited your post, sorry! 
Just to clarify, when you click the search button it only looks through saved BIN files.
If you click Search but don't have anything saved, nothing will show.
In your screenshot, it looks like you have WZ mode selected which I assume means you don't have any data saved. Could you try saving after loading, then try searching again and let me know if that works?

![WzVisualizer_S9hpO5OKSZ](https://user-images.githubusercontent.com/8017468/96177042-7d2a6a80-0eea-11eb-8920-e02a042524bc.png)
My screenshot tested on clean v95 files. Loaded, saved then searched.

I'll see if I can make an update to fix this. Thanks!
