### ISSUE TITLE
Cannot load bin with new version / read wz files

### ISSUE THREAD

**Issue by itay0246** [izarooni/WzVisualizer#6]
Hello, so recently i tried to check some items id with the new version you just released and i came to a problem which my software crash whenever im trying to load from wz files and when i tried to use bin nothing is being load.
i tried to use the older version and everything is working fine but seems like with the new version my software crash for some reason.
Note: i tested it on the same folder
the error seem to be something with net framework.
Details of the error:
`See the end of this message for details on activation
Just-in-time (JIT) debugging instead of this dialog box.

************** Exceptional text ***************
System.NullReferenceException: The object reference is not set to an object instance.
   In WzVisualizer.GUI.MainForm.LoadWzData (Int32 selectedRoot, WzMapleVersion encryption, String directory)
   In WzVisualizer.GUI.MainForm.BtnWzLoad_Click (Object sender, EventArgs e)
   In System.Windows.Forms.Control.OnClick (EventArgs e)
   In System.Windows.Forms.Button.OnClick (EventArgs e)
   In System.Windows.Forms.Button.OnMouseUp (MouseEventArgs mevent)
   In System.Windows.Forms.Control.WmMouseUp (Message & m, MouseButtons button, Int32 clicks)
   In System.Windows.Forms.Control.WndProc (Message & m)
   In System.Windows.Forms.ButtonBase.WndProc (Message & m)
   In System.Windows.Forms.Button.WndProc (Message & m)
   In System.Windows.Forms.NativeWindow.Callback (IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

Thanks for help :)

**Comment by izarooni** [comment]
[WzVisualizer.zip](https://github.com/izarooni/WzVisualizer/files/8597240/WzVisualizer.zip)
Hi! Could you try this update? Seems to be an issue with the way i cache/save data.
I've marked the program as version 1.5.7

**Comment by itay0246** [comment]
> [WzVisualizer.zip](https://github.com/izarooni/WzVisualizer/files/8597240/WzVisualizer.zip) Hi! Could you try this update? Seems to be an issue with the way i cache/save data. I've marked the program as version 1.5.7

thanks for response, i have tried as you asked me and seems like i don't get any error now but the program is just stuck idk if the reason for this is my computer being bad

**Comment by itay0246** [comment]
also bins not being loaded like in the older version

**Comment by izarooni** [comment]
Could you zip and upload the bin files that aren't working? Loading does take a while so give it a bit, then make sure to save if it works so you don't have to load again. The program can use several gigabytes of memory while loading data, it usually takes me a few minutes.

**Comment by itay0246** [comment]
> Could you zip and upload the bin files that aren't working? Loading does take a while so give it a bit, then make sure to save if it works so you don't have to load again. The program can use several gigabytes of memory while loading data, it usually takes me a few minutes.

Sorry i just figured out that the bin is being taken from exports folder and apparently i have old bins in my older version folder im gonna test and see why the wz not being loaded properly

**Comment by itay0246** [comment]
Okay so after i tested everything seem to work fine with version 1.5.7 its just take time to load wz like weapons/overall with many items and my computer is pretty slow, sorry for bothering and thanks for help!

**Comment by izarooni** [comment]
No worries, thanks for using my program!
